In [1]:
import numpy as np

In [6]:
X=np.arange(30)

In [7]:
print(X)
print(type(X))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>


In [9]:
np.arange(22,55)

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [10]:
np.arange(22,69,7)

array([22, 29, 36, 43, 50, 57, 64])

In [11]:
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [12]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [16]:
np.linspace(2,22,6,retstep=True)

(array([ 2.,  6., 10., 14., 18., 22.]), 4.0)

In [19]:
np.linspace(2,22,6,endpoint=False,retstep=True)

(array([ 2.        ,  5.33333333,  8.66666667, 12.        , 15.33333333,
        18.66666667]),
 3.3333333333333335)

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(10)

array([0.34759652, 0.15205721, 0.80832074, 0.38258692, 0.87935664,
       0.75260057, 0.44918474, 0.9399963 , 0.91973485, 0.36800268])

In [24]:
np.random.rand(10)

array([0.84900927, 0.331568  , 0.69579967, 0.65734097, 0.15001198,
       0.01180668, 0.89731544, 0.81219367, 0.07571157, 0.78497543])

In [25]:
np.random.rand(10,5)

array([[0.3159638 , 0.0287124 , 0.43560651, 0.42653183, 0.76631866],
       [0.61423633, 0.06882265, 0.56759574, 0.79851266, 0.65847039],
       [0.37850487, 0.33943266, 0.02987447, 0.18601035, 0.48341308],
       [0.25653107, 0.45859164, 0.08002719, 0.66997333, 0.59928776],
       [0.46500222, 0.77930871, 0.30867503, 0.51002405, 0.8758266 ],
       [0.14090238, 0.02718803, 0.18643888, 0.82723121, 0.06717487],
       [0.84912876, 0.31367677, 0.79591213, 0.29683893, 0.68430821],
       [0.69315758, 0.79180233, 0.17688458, 0.76381892, 0.35838165],
       [0.01316756, 0.74331634, 0.66194941, 0.9752831 , 0.24151789],
       [0.641151  , 0.26427389, 0.813844  , 0.29519725, 0.55868576]])

In [26]:
np.eye(1)

array([[1.]])

In [27]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [28]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [29]:
np.random.randn(4)

array([-1.85430009, -1.02924614,  0.00490647,  0.42545436])

In [30]:
np.random.randn(5,5)

array([[-0.54883107,  1.38783465, -1.83790339, -2.19198609,  0.01133806],
       [-1.11028896,  0.20623234,  1.89132008,  0.05673216,  0.88592529],
       [ 0.10180732, -1.36001187, -1.09434497,  0.95351878,  0.27484644],
       [ 1.4044953 ,  1.07837801, -0.13464189,  0.04139855,  0.96706914],
       [-0.99874095,  0.67888491,  1.04230476, -1.65972334,  0.32340007]])

In [31]:
np.random.randint(10)

9

In [32]:
np.random.randint(20)

18

In [33]:
np.random.randint(20,30)

27

In [34]:
np.random.randint(20,30,6)

array([23, 21, 21, 28, 28, 26])

In [36]:
a=np.random.randint(20,100,50)

In [37]:
a

array([37, 98, 25, 61, 80, 64, 57, 37, 72, 42, 22, 82, 23, 96, 56, 98, 61,
       44, 94, 61, 20, 45, 21, 88, 98, 53, 78, 46, 25, 35, 37, 80, 70, 61,
       78, 93, 36, 56, 70, 42, 41, 69, 42, 97, 91, 37, 75, 27, 69, 42])

In [38]:
a=np.arange(50)

In [39]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [43]:
a.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [44]:
x=np.arange(56)

In [46]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55]


In [48]:
x.reshape(8,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55]])

In [51]:
x=np.random.randint(20,40,10)

In [52]:
x

array([38, 32, 38, 29, 25, 24, 30, 30, 24, 35])

In [53]:
x.max()

38

In [54]:
x.min()

24

In [55]:
x.shape

(10,)

In [56]:
y=x.reshape(2,5)

In [57]:
y

array([[38, 32, 38, 29, 25],
       [24, 30, 30, 24, 35]])

In [58]:
y.shape

(2, 5)

In [60]:
X=np.array([[23,44],[55,67]])

In [61]:
X

array([[23, 44],
       [55, 67]])

In [62]:
X.dtype

dtype('int32')

In [63]:
from numpy.random import randn,randint

In [64]:
randn(5)

array([-0.87862185, -1.09860504,  0.90455215, -0.43273498,  0.40895905])

In [65]:
randn(5,6)

array([[ 0.5878901 ,  0.8315922 , -1.30827966, -1.83059635,  0.75059474,
         1.30567788],
       [ 0.57412847,  1.88888456,  0.09259218,  1.1675724 ,  1.31654092,
        -0.24612021],
       [-0.03587015, -0.58612166, -0.46676627,  0.89860694, -0.1618959 ,
        -1.7215481 ],
       [ 1.19667275, -1.35648294,  0.93646163,  2.26404055,  0.27856543,
        -0.28111734],
       [ 0.55827762,  0.3916796 , -1.65219801, -0.8626564 ,  0.06112028,
        -0.46950452]])

In [66]:
randint(20,30,6)

array([21, 24, 20, 28, 24, 20])

In [67]:
A=['Prashant',44,69,23,'Singh']

In [68]:
B=np.array(A)

In [69]:
B

array(['Prashant', '44', '69', '23', 'Singh'], dtype='<U8')

In [70]:
A

['Prashant', 44, 69, 23, 'Singh']

In [72]:
type(A)


list

In [73]:
type(B)

numpy.ndarray

In [75]:
X=np.array([[23,44,55],[68,59,23],[67,90,23]])

In [76]:
X

array([[23, 44, 55],
       [68, 59, 23],
       [67, 90, 23]])

In [77]:
Y={'Name':'Prashant','Nick':'Rock','Hobby':'Killing'}

In [78]:
X=np.array(Y)

In [79]:
X

array({'Name': 'Prashant', 'Nick': 'Rock', 'Hobby': 'Killing'},
      dtype=object)

In [80]:
A=np.array([['Prashant',44,55],['SOn Goku',59,23],['Zeno',90,23]])

In [81]:
A

array([['Prashant', '44', '55'],
       ['SOn Goku', '59', '23'],
       ['Zeno', '90', '23']], dtype='<U8')

In [82]:
np.zeros(4)

array([0., 0., 0., 0.])

In [84]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [85]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [86]:
np.ones((6,6,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
      

In [91]:
from numpy import array as arr

In [92]:
x=array(67)
y=array([2,3,4,5,6])
z=array([[23,44],[5578,643]])
v=array([[[23,55,66],[78,23,53],[592,37,23]]])
print(x.ndim)
print(y.ndim)
print(z.ndim)
print(v.ndim)

0
1
2
3


In [101]:
a=arr(['Prashant','Hell',45,67,31,78],ndmin=6)
print(a)
print(a.ndim)

[[[[[['Prashant' 'Hell' '45' '67' '31' '78']]]]]]
6


In [104]:
x=arr([34,65,35,789,23,'Prashant'])
x[5]

'Prashant'

In [108]:
print(x[5]+x[0])

Prashant34


In [109]:
XZ=arr([[23,55,66],[69,24,68]])

In [110]:
XZ

array([[23, 55, 66],
       [69, 24, 68]])

In [113]:
XZ[1,1]

24

In [127]:
XY=arr([2,34,63,34,234,43])

In [129]:
XY[2:6]

array([ 63,  34, 234,  43])

In [131]:
XY[-5:-3]

array([34, 63])

In [135]:
XZ=arr([[23,55,66,34,76],[69,24,68,89,32]])

In [136]:
XZ

array([[23, 55, 66, 34, 76],
       [69, 24, 68, 89, 32]])

In [137]:
XZ[1,2:4]

array([68, 89])

In [142]:
XZ[0,3:5]

array([34, 76])