Python Program to Find LCM

In [2]:
def LCM(X,Y):
    if X>Y:
        Largest=X
    else:
        Largest=Y
    while True:
        if Largest%X==0 and Largest%Y==0:
            lcm=Largest
            break
        Largest+=1
    return lcm
A=int(input('Enter The First Number:'))
B=int(input('Enter The Second Number:'))
print('LCM Of',A,'And',B,'Is',LCM(A,B))

Enter The First Number:44
Enter The Second Number:28
LCM Of 44 And 28 Is 308


Python funcction to Find the Factors of a Number

In [4]:
X=int(input('Enter The Number:'))
print('Factors Of',X)
for i in range(1,X+1):
    if X%i==0:
        print(i)

Enter The Number:44
Factors Of 44
1
2
4
11
22
44


Python Program to Make a Simple Calculator

In [5]:
def ADD(X,Y):
    return X+Y
def SUB(X,Y):
    return X-Y
def MUL(X,Y):
    return X*Y
def DIV(X,Y):
    return X/Y
print('Which Operation You Want To Use:')
print('1.Addition\n2.Subtraction\n3.Multiplication\n4.Division')
Z=input('Enter Your Choice 1 2 3 4')
A=int(input('Enter The First Number:'))
B=int(input('Enter The Second Number:'))
if Z=='1':
    print('Addition=',ADD(A,B))
elif Z=='2':
    print('Subtraction=',SUB(A,B))
elif Z=='3':
    print('Multiplication=',MUL(A,B))
elif Z=='4':
    print('Division=',DIV(A,B))
else:
    print('Wrong Choice')

Which Operation You Want To Use:
1.Addition
2.Subtraction
3.Multiplication
4.Division
Enter Your Choice 1 2 3 43
Enter The First Number:34
Enter The Second Number:55
Multiplication= 1870


Another Type

In [8]:
def Cal():
    print('Which Operation You Want To Use:')
    print('1.Addition\n2.Subtraction\n3.Multiplication\n4.Division')
    X=int(input('Enter The First Number:'))
    Y=int(input('Enter The Second Number:'))
    Z=input('Enter Your Choice 1 2 3 4')
    if Z=='1':
        print('Addition=',X+Y)
    elif Z=='2':
        print('Subtraction=',X-Y)
    elif Z=='3':
        print('Multiplication=',X*Y)
    elif Z=='4':
        print('Division=',X/Y)
    else:
        print('Wrong Choice')
    Again()
def Again():
    A=input('Want To Calculate Again.If Yes Press Y and No Press N:')
    if A.upper()=='Y':
        Cal()
    elif A.upper()=='N':
        print('Mata ne')
    else:
        again()

In [9]:
Cal()

Which Operation You Want To Use:
1.Addition
2.Subtraction
3.Multiplication
4.Division
Enter The First Number:56
Enter The Second Number:26
Enter Your Choice 1 2 3 44
Division= 2.1538461538461537
Want To Calculate Again.If Yes Press Y and No Press N:y
Which Operation You Want To Use:
1.Addition
2.Subtraction
3.Multiplication
4.Division
Enter The First Number:23
Enter The Second Number:44
Enter Your Choice 1 2 3 43
Multiplication= 1012
Want To Calculate Again.If Yes Press Y and No Press N:n
Mata ne


Python Program to Display Fibonacci Sequence Using Recursion

In [11]:
def Fibo(X):
    if X<=1:
        return X
    else:
        return Fibo(X-1)+Fibo(X-2)
Y=int(input('Enter The Number Of Terms'))
if Y<=0:
    print('Enter The Positive Number')
else:
    print('Fibonacci Series:')
    for i in range(Y):
        print(Fibo(i))

Enter The Number Of Terms10
Fibonacci Series:
0
1
1
2
3
5
8
13
21
34


Python Program to Find Sum of Natural Numbers Using Recursion

In [12]:
def SN(X):
    if X<=1:
        return X
    else:
        return X+SN(X-1)
Y=int(input('Enter The Terms Of The Natural Numbers:'))
if Y<=0:
    print('No Negative Number')
else:
    print('Sum Of',Y,'Natural Numbers=',SN(Y))

Enter The Terms Of The Natural Numbers:23
Sum Of 23 Natural Numbers= 276


Python Program to Find Factorial of Number Using Recursion

In [14]:
def FN(X):
    if X<=1:
        return X
    else:
        return X*FN(X-1)
Y=int(input('Enter The Number'))
if Y<=0:
    print('No No!!Only Positive')
else:
    print('Factorial Of',Y,'Is ',FN(Y))

Enter The Number55
Factorial Of 55 Is  12696403353658275925965100847566516959580321051449436762275840000000000000


Python Program to Add Two Matrices

In [22]:
x=[[2,3,4],
  [34,23,55],
  [68,74,33]]
y=[[33,44,56],
  [66,77,88],
  [67,34,66]]
R=[[0,0,0],
         [0,0,0],
         [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        R[i][j]=x[i][j]+y[i][j]
for k in R:
    print(k)

[35, 47, 60]
[100, 100, 143]
[135, 108, 99]


w.a.p. to enter purchase amount and calculate discount on the basis of amount.
	if amount >=30000 then discount will be 30%
	if amount>=20000 and <30000 then discount will be 20%
	if amount>=10000 and <20000 then discount will be 10%
	else discount will be 3%.
	also calculate payable amount .

In [23]:
X=int(input('Enter The Amt:'))
if X<10000:
    print('Discount Will Be 3%')
    print('After Discount Price will be:',X*.03)
elif 10000<=X<20000:
    print('Discount Will Be 10%')
    print('After Discount Price will be:',X*.1)
elif 20000<=X<30000:
    print('Discount Will Be 20%')
    print('After Discount Price will be:',X*.2)
else:
    print('Discount Will Be 30%')
    print('After Discount Price will be:',X*.3)

Enter The Amt:45553
Discount Will Be 30%
After Discount Price will be: 13665.9


Python Program to Transpose a Matrix using Nested Loop

In [32]:
from numpy import array as arr

In [35]:
X=arr([[23,53,23],[673,43,55],[89,67,99]])
print(X)
print('After Transpose')
R=arr([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(X)):
    for j in range(len(X[0])):
        R[j][i]=X[i][j]
for k in R:
    print(k)

[[ 23  53  23]
 [673  43  55]
 [ 89  67  99]]
After Transpose
[ 23 673  89]
[53 43 67]
[23 55 99]


Python Program to Multiply Two Matrices using Nested Loop

In [41]:
X=arr([[23,44,55],[12,54,78],[79,89,99]])
Y=arr([[55,64,24,3],[23,57,34,44],[32,45,24,223]])
print(X,'\n\n',Y)
R=arr([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print('After Multiplication')
for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            R[i][j]+=X[i][k]*Y[k][j]
for l in R:
    print(l)

[[23 44 55]
 [12 54 78]
 [79 89 99]] 

 [[ 55  64  24   3]
 [ 23  57  34  44]
 [ 32  45  24 223]]
After Multiplication
[ 4037  6455  3368 14270]
[ 4398  7356  3996 19806]
[ 9560 14584  7298 26230]


Python Program to Check Whether a String is Palindrome or Not

In [42]:
def SP(Y):
    return Y==Y[::-1]
X='PrashantHell'
Z=SP(X)
if Z:
    print('Palindrom')
else:
    print('Not A Palindrome')

Not A Palindrome
